  
version: '3'
services:
  elasticsearch:
    image: "elasticsearch:7.10.1"
    networks:
      - frontend
    restart: always
    volumes:
      - ./ES_Data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      retries: 6
  
  agriapp:
    image: "agriapp:1.0"
    networks:
     - frontend
    ports:
      - 5000:5000
      
networks:
    frontend: